### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by cardillan** [cardillan/mindcode#1]
- [x] chained ternary operator produces wrong code
- [x] move removal of always false jumps to ConditionalJumpsNormalizer
- [x] use Opcode metadata in LogicInstructionGenerator
- [x] investigate if uradar is working (both compiler - there's an unitialized tmp, and DeadCodeEliminator - marks built-in arguments as reads) - see https://github.com/francois/mindcode/issues/51
- [x] check end/reaching end of the list/jump to 0 behaves the same in v6/v7
- [x] automatically generate (markdown) document describing functions based on (enhanced) Opcode metadata.
- [ ] Improve compiler error messages

## Syntax Wishlist
- [x] range expressions (like ranges, except the start and end would be expressions, not int literals) -- permissible in range iteration loops
- [x] multiple alternatives per case when (`case type when @container, @vault 1 else 0 end`)
- [x] range expression in case when alternatives (`case state when 1 .. 5 ...`)
- [x] do while loop (probably in the form of `do loop_body loop while condition`)
- [x] foreach loops, such as `for type in [@mono, @poly, @mega] ubind(type) ... end` - the list would be hard-coded into code (two or three instructions per item)
- [ ] short-circuit boolean eval (a first step could be just a specific optimization for this)
- [x] improved functions (inline functions, stackless functions and recursive functions - see below) 
- [x] constants and constant expressions
  - not preserved as variables in compiled code
  - evaluated at compile time
  - integers at first, but could be strings or booleans too
- [ ] lookup table-supported case expressions (see below)
- [ ] labels and jumps (effectively a goto :raised_eyebrow:) 

### Lookup table-supported case expressions
- A case over integer expression where the target address is loaded from a lookup table inside a memory.
- Needs a code to initialize the lookup table and the statement itself. The syntax must support splitting the two statements, as the lookup table needs to be initialized just once, while the case can be called in a loop repeatedly
- The when alternatives must be integer constants.
- Possible syntax:

```
allocate lookup table <lookup_identifier> range <const_min> .. <const_max> in <memory>
...
case <expression> using <lookup_identifier>
    when <numerical constant>
        ....
    when <numerical constant>
        ....
    else 
        ....
end

```
- Each allocate lookup table must be matched with exactly one case using that lookup table
- Thinking about ways to allow fall-through:
   - `continue` (or `fallthrough`?) keyword
- The value of the case expression will be min/maxed to the range of `first_state - 1 .. last_state + 1` (two op instructions) and the two corresponding memory cells will be set to target the else branch. Additional instruction will be the offset.

Or just allow using jumps/labels and assigning labels to variables and let the user build it himself.

### Function improvements
- Inline functions:
   - declared as such (`inline def ... end`)
   - cannot be recursed
- other functions: the compiler will create and analyze the call graph (oriented graph). Functions that are part of a cycle must be always called via stack. Functions not part of the cycle will never be recursed, and can use variables to pass input/output values and return address.
- recursive functions:
   - store stack in __sp variable, not in external memory.
   - perhaps virtual push/pop instruction which would be resolved by the optimizers/code printers (? not sure how useful)
- if there are no recursive functions, no stack allocation is necessary.

**Comment by cardillan** [comment]
Everything was moved to main readme file.
